Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,40 +1,26 @@
 steps:
-  - name: 'gcr.io/cloud-builders/git'
-    args:
-      - 'clone'
-      - 'https://github.com/shlokie1999/MoviePilot'
-      - '/workspace/source'
+  - name: 'gcr.io/cloud-builders/docker'
+    args: ['build', '-t','us-central1-docker.pkg.dev/mcmp-integration-qa/mend-bolt/myimage:latest', '.']
+    
+  - name: 'us-central1-docker.pkg.dev/mcmp-integration-qa/mend-bolt/myimage:latest'
+    args: ['curl', '-s', '-L', '-O', 'https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh']
 
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        apt-get update && apt-get install -y wget tar golang git
-        wget https://github.com/zricethezav/gitleaks/releases/download/v8.15.3/gitleaks_8.15.3_linux_x64.tar.gz #Download the release 
-        mkdir gitleaks
-        tar -xvzf gitleaks_8.15.3_linux_x64.tar.gz
-        chmod +x gitleaks # Set permision
-        mv gitleaks /usr/bin/
-        gitleaks -h  # Support for command flags
-        gitleaks detect --source /workspace/source -v --report-path /workspace/gitleaks-report.json --exit-code 0 --redact --no-git  # Run Gitleaks Command
-
-  - name: 'gcr.io/cloud-builders/gsutil'
-    args: ['cp', 'gitleaks-report.json', 'gs://testingleaks/gitleaks-report.json']
+  # - name: 'gcr.io/cloud-builders/gsutil'
+  #   args: ['cp', 'gitleaks-report.json', 'gs://testingleaks/gitleaks-report.json']
   
-  - name: 'ubuntu'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        report= cat /workspace/gitleaks-report.json
-        echo $report
-        if [ "$report" = "[]" ]; then
-          echo "No leaks found. Continuing build."
-        else
-          echo "Leaks detected. Failing build."
-          exit 1
-        fi
+  # - name: 'ubuntu'
+  #   entrypoint: 'bash'
+  #   args:
+  #     - '-c'
+  #     - |
+  #       report= cat /workspace/gitleaks-report.json
+  #       echo $report
+  #       if [ "$report" = "[]" ]; then
+  #         echo "No leaks found. Continuing build."
+  #       else
+  #         echo "Leaks detected. Failing build."
+  #         exit 1
+  #       fi
         
   
 # artifacts:
